models:
 "<model_name>":
   api_type: "openai"
   base_url: "<your base url>"
   api_key: "<your api key>"
   temperature: 0
 "<model_name>":
   api_type: "openai"
   base_url: "<your base url>"
   api_key: "<your api key>"
   temperature: 0