models:
  "gpt-4o-mini":
    api_type: "openai"
    base_url: "https://api.linkapi.org/v1"
    api_key: "sk-XilSri6YnWxgj96h3rvrHjAWl4Qly8GNu9ZWwfxpwdxN0plk"
    temperature: 0.3
  "gpt-4":
    api_type: "openai"
    base_url: "https://api.linkapi.org/v1"
    api_key: "sk-XilSri6YnWxgj96h3rvrHjAWl4Qly8GNu9ZWwfxpwdxN0plk"
    temperature: 0.3